spring:
  application:
    name: okta

  datasource:
    url: jdbc:postgresql://localhost:5432/okta_app_db
    username: postgres
    password: T@b1sh#004$psql

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true